=== arkadiuszgrabowski/Programowanie-komunikacji-czlowiek-komputer/PKCK/Zadanie1/dtd_zadanie1.dtd
<!ENTITY % TypeOfOrder "(New|Processing|Complete|Closed|Canceled)"> 
<!ELEMENT Company (Authors, ProductsRepository, Orders)>

<!ELEMENT Authors (Author+)>
<!ELEMENT Author EMPTY>
<!ATTLIST Author Forename CDATA #REQUIRED Name CDATA #REQUIRED AuthorId CDATA #REQUIRED>

<!ELEMENT ProductsRepository (Product+)>
<!ELEMENT Product (Name, ProductPrice)>
<!ATTLIST Product ProductId ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT ProductPrice (#PCDATA)>

<!ELEMENT Orders (Order+)>
<!ELEMENT Order (Items, Address, SendingDateTime, EstimatedDelivery, OrderPrice)>
<!ATTLIST Order OrderId ID #REQUIRED OrderType CDATA #REQUIRED>
<!ELEMENT Items (Item+)>
<!ELEMENT Item (Quantity)>
<!ATTLIST Item ProductId IDREF #REQUIRED>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Address (City, Street, Property, ZipCode)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT Property (#PCDATA)>
<!ELEMENT ZipCode (#PCDATA)>
<!ELEMENT SendingDateTime (#PCDATA)>
<!ELEMENT EstimatedDelivery (#PCDATA)>
<!ELEMENT OrderPrice (#PCDATA)>

=== arkadiuszgrabowski/Programowanie-komunikacji-czlowiek-komputer/PKCK/Zadanie1/zadanie1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE Company SYSTEM "dtd_zadanie1.dtd">
<Company>
  <Authors>
    <Author Forename="Arkadiusz" Name="Grabowski" AuthorId="210191" />
    <Author Forename="Kacper" Name="Prądzyński" AuthorId="210299" />
  </Authors>
  <ProductsRepository>
    <Product ProductId="xc3f8b6e1-d559-4690-85e2-c4537b6c97af">
      <Name>Śrubka 2x3mm</Name>
      <ProductPrice>10.5</ProductPrice>
    </Product>
    <Product ProductId="xb63d4c0a-2d27-47db-820d-570eb3a12bc6">
      <Name>Monitor Asus 24 cale</Name>
      <ProductPrice>1299.99</ProductPrice>
    </Product>
    <Product ProductId="xab3c4009-b0e6-4226-a398-45267a62eb9e">
      <Name>Karta graficzna GeForce RTX 2080Ti</Name>
      <ProductPrice>4699.99</ProductPrice>
    </Product>
    <Product ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
      <Name>Klawiatura Roccat MK Ryos</Name>
      <ProductPrice>359.9</ProductPrice>
    </Product>
    <Product ProductId="x6fd72d84-3ca6-4cde-bf5c-2701e12ce01b">
      <Name>Macbook Air 2018</Name>
      <ProductPrice>4999.99</ProductPrice>
    </Product>
    <Product ProductId="x430f31d1-9e70-44b9-b9ff-afb45a8f7ed6">
      <Name>Lenovo Y520</Name>
      <ProductPrice>3599.49</ProductPrice>
    </Product>
    <Product ProductId="x2b55c6e5-60ad-46f6-96d0-73c077cb8d4d">
      <Name>Xiaomi Redmi 4X</Name>
      <ProductPrice>5000.99</ProductPrice>
    </Product>
    <Product ProductId="x6ae2acf5-69ed-49cc-a59a-7485980f6e92">
      <Name>Lg G7 Thinq</Name>
      <ProductPrice>4999.99</ProductPrice>
    </Product>
    <Product ProductId="x1fee4f0a-481a-4d4d-84e2-65f2d41e27bc">
      <Name>Windows 10 Pro</Name>
      <ProductPrice>789.99</ProductPrice>
    </Product>
    <Product ProductId="x40b4dbf3-b20e-4bc2-b14e-14e1f0bc10d6">
      <Name>Iphone Xs</Name>
      <ProductPrice>10099.99</ProductPrice>
    </Product>
    <Product ProductId="xc9d779a9-be03-422c-bcb2-39435bcf549c">
      <Name>Pad Xbox 360</Name>
      <ProductPrice>120.99</ProductPrice>
    </Product>
    <Product ProductId="x9aa9c06b-713b-4a1c-b2f9-8b2e0a91b54c">
      <Name>Myszka Lenovo</Name>
      <ProductPrice>9.99</ProductPrice>
    </Product>
  </ProductsRepository>
  <Orders>
    <Order OrderId="xf7b3d5f9-9921-4d77-92ca-cd2b7171c8d1" OrderType="Complete">
      <Items>
        <Item ProductId="xb63d4c0a-2d27-47db-820d-570eb3a12bc6">
          <Quantity>2</Quantity>
        </Item>
        <Item ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
          <Quantity>5</Quantity>
        </Item>
        <Item ProductId="x2b55c6e5-60ad-46f6-96d0-73c077cb8d4d">
          <Quantity>2</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Łódź</City>
        <Street>Politechniki</Street>
        <Property>3a</Property>
        <ZipCode>93-501</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-18</EstimatedDelivery>
      <OrderPrice>14401.46</OrderPrice>
    </Order>
    <Order OrderId="x4c97091e-eba5-42cf-87d8-7c315237f399" OrderType="New">
      <Items>
        <Item ProductId="xc3f8b6e1-d559-4690-85e2-c4537b6c97af">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
          <Quantity>5</Quantity>
        </Item>
        <Item ProductId="x1fee4f0a-481a-4d4d-84e2-65f2d41e27bc">
          <Quantity>1</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Łęczyca</City>
        <Street>Belwederska</Street>
        <Property>79a</Property>
        <ZipCode>99-100</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-20</EstimatedDelivery>
      <OrderPrice>2599.99</OrderPrice>
    </Order>
    <Order OrderId="xe0d89dc0-b4f5-4187-8860-82bc056506ac" OrderType="Canceled">
      <Items>
        <Item ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
          <Quantity>5</Quantity>
        </Item>
        <Item ProductId="x9aa9c06b-713b-4a1c-b2f9-8b2e0a91b54c">
          <Quantity>1</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Szczecin</City>
        <Street>Wąska 74</Street>
        <Property>74</Property>
        <ZipCode>71-407</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-21</EstimatedDelivery>
      <OrderPrice>1809.49</OrderPrice>
    </Order>
    <Order OrderId="xb3428863-5f81-47f0-832e-12a64bad2ae0" OrderType="Canceled">
      <Items>
        <Item ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
          <Quantity>5</Quantity>
        </Item>
        <Item ProductId="x9aa9c06b-713b-4a1c-b2f9-8b2e0a91b54c">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="x430f31d1-9e70-44b9-b9ff-afb45a8f7ed6">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="xc9d779a9-be03-422c-bcb2-39435bcf549c">
          <Quantity>10</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Gdynia</City>
        <Street>Sieroszewskiego Wacława</Street>
        <Property>141</Property>
        <ZipCode>81-376</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-18</EstimatedDelivery>
      <OrderPrice>6618.88</OrderPrice>
    </Order>
    <Order OrderId="x82d47e0f-166a-43f6-ac41-dd95f879ea38" OrderType="Processing">
      <Items>
        <Item ProductId="xc3f8b6e1-d559-4690-85e2-c4537b6c97af">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="xb63d4c0a-2d27-47db-820d-570eb3a12bc6">
          <Quantity>2</Quantity>
        </Item>
        <Item ProductId="xab3c4009-b0e6-4226-a398-45267a62eb9e">
          <Quantity>3</Quantity>
        </Item>
        <Item ProductId="x400edcf8-e461-478f-9f1d-9d205e9a2f6a">
          <Quantity>5</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Brzeg</City>
        <Street>Kruszyńska</Street>
        <Property>73</Property>
        <ZipCode>49-300</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-19</EstimatedDelivery>
      <OrderPrice>18509.95</OrderPrice>
    </Order>
    <Order OrderId="x555e7f1a-71c5-4330-86fa-34528f3fab4e" OrderType="Complete">
      <Items>
        <Item ProductId="x6fd72d84-3ca6-4cde-bf5c-2701e12ce01b">
          <Quantity>6</Quantity>
        </Item>
        <Item ProductId="x430f31d1-9e70-44b9-b9ff-afb45a8f7ed6">
          <Quantity>1</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Łódź</City>
        <Street>Legionów</Street>
        <Property>114</Property>
        <ZipCode>91-072</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-17</EstimatedDelivery>
      <OrderPrice>33599.43</OrderPrice>
    </Order>
    <Order OrderId="x086fce45-6b57-47e6-9726-adc7e220443e" OrderType="Processing">
      <Items>
        <Item ProductId="x6ae2acf5-69ed-49cc-a59a-7485980f6e92">
          <Quantity>3</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Sopot</City>
        <Street>Herberta Zbigniewa</Street>
        <Property>109</Property>
        <ZipCode>81-826</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-22</EstimatedDelivery>
      <OrderPrice>14999.97</OrderPrice>
    </Order>
    <Order OrderId="x82a12e8d-70cf-48e5-b578-b3d3c8d07fc5" OrderType="Canceled">
      <Items>
        <Item ProductId="x1fee4f0a-481a-4d4d-84e2-65f2d41e27bc">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="x40b4dbf3-b20e-4bc2-b14e-14e1f0bc10d6">
          <Quantity>6</Quantity>
        </Item>
        <Item ProductId="xc9d779a9-be03-422c-bcb2-39435bcf549c">
          <Quantity>10</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Opole</City>
        <Street>Kielecka</Street>
        <Property>65/24</Property>
        <ZipCode>45-401</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-20</EstimatedDelivery>
      <OrderPrice>62599.83</OrderPrice>
    </Order>
    <Order OrderId="x7cc962cc-55e7-4de1-af7c-bd88143dfb57" OrderType="Complete">
      <Items>
        <Item ProductId="x9aa9c06b-713b-4a1c-b2f9-8b2e0a91b54c">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="xc9d779a9-be03-422c-bcb2-39435bcf549c">
          <Quantity>10</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Warszawa</City>
        <Street>Nowy Świat</Street>
        <Property>133/67</Property>
        <ZipCode>00-400</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-18</EstimatedDelivery>
      <OrderPrice>1219.89</OrderPrice>
    </Order>
    <Order OrderId="xabda25be-3343-406e-9769-bb1c3515eda5" OrderType="Complete">
      <Items>
        <Item ProductId="x40b4dbf3-b20e-4bc2-b14e-14e1f0bc10d6">
          <Quantity>6</Quantity>
        </Item>
        <Item ProductId="x1fee4f0a-481a-4d4d-84e2-65f2d41e27bc">
          <Quantity>1</Quantity>
        </Item>
        <Item ProductId="x6ae2acf5-69ed-49cc-a59a-7485980f6e92">
          <Quantity>3</Quantity>
        </Item>
        <Item ProductId="x2b55c6e5-60ad-46f6-96d0-73c077cb8d4d">
          <Quantity>2</Quantity>
        </Item>
        <Item ProductId="x430f31d1-9e70-44b9-b9ff-afb45a8f7ed6">
          <Quantity>1</Quantity>
        </Item>
      </Items>
      <Address>
        <City>Białystok</City>
        <Street>Zagórki</Street>
        <Property>106</Property>
        <ZipCode>15-587</ZipCode>
      </Address>
      <SendingDateTime>2019-03-16 21:07:16</SendingDateTime>
      <EstimatedDelivery>2019-03-21</EstimatedDelivery>
