=== arkadiuszgrabowski/Programowanie-komunikacji-czlowiek-komputer/PKCK/Zadanie2/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:zam="zam"
targetNamespace="zam" elementFormDefault="qualified">

    <xs:group name="AddressGroup">
        <xs:sequence>
            <xs:element name="City" type="xs:string" />
            <xs:element name="Street">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:whiteSpace value="preserve" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Property" type="xs:string" />
            <xs:element name="ZipCode">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{2}-\d{3}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="Address">
        <xs:sequence>
            <xs:group ref="zam:AddressGroup"></xs:group>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Author">
            <xs:attribute name="Forename" type="xs:string"/>
            <xs:attribute name="Name" type="xs:string"/>
            <xs:attribute name="AuthorId">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:totalDigits value="6" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Product">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="ProductPrice">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0.01" />
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ProductId" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="x\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Item">
        <xs:sequence>
            <xs:element name="Quantity">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:totalDigits value="3" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ProductId" use="required" >
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="x\w{8}-\w{4}-\w{4}-\w{4}-\w{12}" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Order">
        <xs:sequence>
            <xs:element name="Items">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Item" type="zam:Item" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Address" type="zam:Address"/>
            <xs:element name="SendingDateTime" type="xs:dateTime"></xs:element>
            <xs:element name="EstimatedDelivery" type="xs:date"></xs:element>
            <xs:element name="OrderPrice">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.01" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="OrderId" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="x\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="OrderType">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="New" />
                    <xs:enumeration value="Processing" />
                    <xs:enumeration value="Complete" />
                    <xs:enumeration value="Closed" />
                    <xs:enumeration value="Canceled" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "Authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Author" type="zam:Author" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ProductsRepository">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Product" type="zam:Product" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Orders">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Order" type="zam:Order" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="productIdKey">
            <xs:selector xpath="Company/ProductsRepository/Product" />
            <xs:field xpath="@ProductId" />
        </xs:key>
        <xs:keyref name="productIdKeyRef" refer="zam:productIdKey">
            <xs:selector xpath="Company/Orders/Order/Items/Item" />
            <xs:field xpath="@ProductId" />
        </xs:keyref>
    </xs:element>
</xs:schema>

=== arkadiuszgrabowski/Programowanie-komunikacji-czlowiek-komputer/XMLGenerator/Data/zadanie1.xml
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="xhtml.xsl"?><Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="zam schema.xsd" xmlns="zam"><Authors><Author Forename="Arkadiusz" Name="Grabowski" AuthorId="210191" /><Author Forename="Kacper" Name="Prądzyński" AuthorId="210299" /></Authors><ProductsRepository><Product ProductId="xdbf19fa3-822c-46a6-856a-dab615521e3b"><Name>Śrubka 2x3mm</Name><ProductPrice>10.5</ProductPrice></Product><Product ProductId="xa57f2a29-9dce-4390-81d0-4207dacf8a6e"><Name>Monitor Asus 24 cale</Name><ProductPrice>1299.99</ProductPrice></Product><Product ProductId="x12ea29fc-ed94-472d-a3d2-adcef4e0442f"><Name>Karta graficzna GeForce RTX 2080Ti</Name><ProductPrice>4699.99</ProductPrice></Product><Product ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Name>Klawiatura Roccat MK Ryos</Name><ProductPrice>359.9</ProductPrice></Product><Product ProductId="x6a70a524-6ed1-4ba9-bfc1-0756487e6872"><Name>Macbook Air 2018</Name><ProductPrice>4999.99</ProductPrice></Product><Product ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Name>Lenovo Y520</Name><ProductPrice>3599.49</ProductPrice></Product><Product ProductId="xa5d6f09d-fb5d-44ba-9f0e-335538988d61"><Name>Xiaomi Redmi 4X</Name><ProductPrice>5000.99</ProductPrice></Product><Product ProductId="xbc91fb8e-0262-4a3e-bb11-5fcbe495ed46"><Name>Lg G7 Thinq</Name><ProductPrice>4999.99</ProductPrice></Product><Product ProductId="x3c438147-55db-45eb-b164-f123da3d7587"><Name>Windows 10 Pro</Name><ProductPrice>789.99</ProductPrice></Product><Product ProductId="xeb3e05c5-d51b-4e5d-bc6b-c955bd9cf9db"><Name>Iphone Xs</Name><ProductPrice>10099.99</ProductPrice></Product><Product ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Name>Pad Xbox 360</Name><ProductPrice>120.99</ProductPrice></Product><Product ProductId="xeb32c79d-a820-4ac9-9e1d-a10c2efd6c35"><Name>Myszka Lenovo</Name><ProductPrice>9.99</ProductPrice></Product></ProductsRepository><Orders><Order OrderId="x5977aece-7bd2-4083-8c7c-ecc0c3d16faf" OrderType="Complete"><Items><Item ProductId="xa57f2a29-9dce-4390-81d0-4207dacf8a6e"><Quantity>2</Quantity></Item><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item><Item ProductId="xa5d6f09d-fb5d-44ba-9f0e-335538988d61"><Quantity>2</Quantity></Item></Items><Address><City>Łódź</City><Street>Politechniki</Street><Property>3a</Property><ZipCode>93-501</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-15</EstimatedDelivery><OrderPrice>14401.46</OrderPrice></Order><Order OrderId="xec5e997f-f408-4509-84fb-a66e02b4377e" OrderType="New"><Items><Item ProductId="xdbf19fa3-822c-46a6-856a-dab615521e3b"><Quantity>1</Quantity></Item><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item><Item ProductId="x3c438147-55db-45eb-b164-f123da3d7587"><Quantity>1</Quantity></Item></Items><Address><City>Łęczyca</City><Street>Belwederska</Street><Property>79a</Property><ZipCode>99-100</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-17</EstimatedDelivery><OrderPrice>2599.99</OrderPrice></Order><Order OrderId="x9092e102-4be5-4d51-a086-ad4262b3c63a" OrderType="Canceled"><Items><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item><Item ProductId="xeb32c79d-a820-4ac9-9e1d-a10c2efd6c35"><Quantity>1</Quantity></Item></Items><Address><City>Szczecin</City><Street>Wąska 74</Street><Property>74</Property><ZipCode>71-407</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-18</EstimatedDelivery><OrderPrice>1809.49</OrderPrice></Order><Order OrderId="x23f55aee-f418-4ac5-86b0-2375f3f78f7e" OrderType="Canceled"><Items><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item><Item ProductId="xeb32c79d-a820-4ac9-9e1d-a10c2efd6c35"><Quantity>1</Quantity></Item><Item ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Quantity>1</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Quantity>10</Quantity></Item></Items><Address><City>Gdynia</City><Street>Sieroszewskiego Wacława</Street><Property>141</Property><ZipCode>81-376</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-15</EstimatedDelivery><OrderPrice>6618.88</OrderPrice></Order><Order OrderId="x6b6ebb36-1eb0-4c5c-b60f-5ece27929adc" OrderType="Processing"><Items><Item ProductId="xdbf19fa3-822c-46a6-856a-dab615521e3b"><Quantity>1</Quantity></Item><Item ProductId="xa57f2a29-9dce-4390-81d0-4207dacf8a6e"><Quantity>2</Quantity></Item><Item ProductId="x12ea29fc-ed94-472d-a3d2-adcef4e0442f"><Quantity>3</Quantity></Item><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item></Items><Address><City>Brzeg</City><Street>Kruszyńska</Street><Property>73</Property><ZipCode>49-300</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-16</EstimatedDelivery><OrderPrice>18509.95</OrderPrice></Order><Order OrderId="xf397ae5b-bb8c-4f8a-8913-4d49f4b216d0" OrderType="Complete"><Items><Item ProductId="x6a70a524-6ed1-4ba9-bfc1-0756487e6872"><Quantity>6</Quantity></Item><Item ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Quantity>1</Quantity></Item></Items><Address><City>Łódź</City><Street>Legionów</Street><Property>114</Property><ZipCode>91-072</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-14</EstimatedDelivery><OrderPrice>33599.43</OrderPrice></Order><Order OrderId="x0b5a51ad-e967-4dd2-9ef6-a91c13cf1b5b" OrderType="Processing"><Items><Item ProductId="xbc91fb8e-0262-4a3e-bb11-5fcbe495ed46"><Quantity>3</Quantity></Item></Items><Address><City>Sopot</City><Street>Herberta Zbigniewa</Street><Property>109</Property><ZipCode>81-826</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-19</EstimatedDelivery><OrderPrice>14999.97</OrderPrice></Order><Order OrderId="xf2412029-5a76-472f-8cb8-f9288cab3803" OrderType="Canceled"><Items><Item ProductId="x3c438147-55db-45eb-b164-f123da3d7587"><Quantity>1</Quantity></Item><Item ProductId="xeb3e05c5-d51b-4e5d-bc6b-c955bd9cf9db"><Quantity>6</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Quantity>10</Quantity></Item></Items><Address><City>Opole</City><Street>Kielecka</Street><Property>65/24</Property><ZipCode>45-401</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-17</EstimatedDelivery><OrderPrice>62599.83</OrderPrice></Order><Order OrderId="xa73ec832-a92a-4a7f-bc38-6451bba94e54" OrderType="Complete"><Items><Item ProductId="xeb32c79d-a820-4ac9-9e1d-a10c2efd6c35"><Quantity>1</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Quantity>10</Quantity></Item></Items><Address><City>Warszawa</City><Street>Nowy Świat</Street><Property>133/67</Property><ZipCode>00-400</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-15</EstimatedDelivery><OrderPrice>1219.89</OrderPrice></Order><Order OrderId="x66322444-456b-4fde-a18b-ed4f3832b6b0" OrderType="Complete"><Items><Item ProductId="xeb3e05c5-d51b-4e5d-bc6b-c955bd9cf9db"><Quantity>6</Quantity></Item><Item ProductId="x3c438147-55db-45eb-b164-f123da3d7587"><Quantity>1</Quantity></Item><Item ProductId="xbc91fb8e-0262-4a3e-bb11-5fcbe495ed46"><Quantity>3</Quantity></Item><Item ProductId="xa5d6f09d-fb5d-44ba-9f0e-335538988d61"><Quantity>2</Quantity></Item><Item ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Quantity>1</Quantity></Item></Items><Address><City>Białystok</City><Street>Zagórki</Street><Property>106</Property><ZipCode>15-587</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-18</EstimatedDelivery><OrderPrice>89991.37</OrderPrice></Order><Order OrderId="xfaa7b4a2-3ee0-43d3-b018-d4e1d262f6e2" OrderType="Canceled"><Items><Item ProductId="x6a70a524-6ed1-4ba9-bfc1-0756487e6872"><Quantity>6</Quantity></Item><Item ProductId="x2704c3ff-60b8-47f4-b37b-862b61819531"><Quantity>5</Quantity></Item></Items><Address><City>Łódź</City><Street>Łęczycka</Street><Property>65/11</Property><ZipCode>93-193</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-23</EstimatedDelivery><OrderPrice>31799.44</OrderPrice></Order><Order OrderId="xbcb0ef3a-61c6-4a97-a5f3-6e1693c1c4e0" OrderType="Canceled"><Items><Item ProductId="x12ea29fc-ed94-472d-a3d2-adcef4e0442f"><Quantity>3</Quantity></Item><Item ProductId="xa57f2a29-9dce-4390-81d0-4207dacf8a6e"><Quantity>2</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Quantity>10</Quantity></Item></Items><Address><City>Wrocław</City><Street>Jagiellońska</Street><Property>63</Property><ZipCode>51-218</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-24</EstimatedDelivery><OrderPrice>17909.85</OrderPrice></Order><Order OrderId="x63a07421-282e-49c0-abd9-1cf7a995776b" OrderType="Canceled"><Items><Item ProductId="xa57f2a29-9dce-4390-81d0-4207dacf8a6e"><Quantity>2</Quantity></Item><Item ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Quantity>1</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d91371"><Quantity>10</Quantity></Item></Items><Address><City>Łódź</City><Street>Łęczycka</Street><Property>65/11</Property><ZipCode>93-193</ZipCode></Address><SendingDateTime>2019-06-13T15:12:59</SendingDateTime><EstimatedDelivery>2019-06-25</EstimatedDelivery><OrderPrice>7409.37</OrderPrice></Order><Order OrderId="x6669d058-e7ce-4cd3-a00d-06a48a25708e" OrderType="Canceled"><Items><Item ProductId="xeb3e05c5-d51b-4e5d-bc6b-c955bd9cf9db"><Quantity>6</Quantity></Item><Item ProductId="xd6002fcc-6c64-4d20-afca-23470c26e869"><Quantity>1</Quantity></Item><Item ProductId="x40c328fa-1aa4-4d27-ab37-73e9c7d9137
